services:

# Basic server
  nginx:
    image: nginx
    container_name: nginx_dev
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./pong:/var/www/pong
    env_file: .env
    depends_on:
      - backend_services
    ports:
      - "${BACKEND_SERVER_SSH_PORT}:443"
      - "${BACKEND_SERVER_PORT}:80"
      - "5173:5173"
      - 5555:5555
    networks:
      - transcendence_network
    restart: unless-stopped

# Authentification service:
  auth_services:
    container_name: auth_service
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    volumes:
      - ./auth-service/app:/app
      - ./auth-service/app/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - sqlite-service
    networks:
      - transcendence_network

 #backend_services:     
  backend_services:
    container_name: backend_services
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - sqlite-service
      - auth_services
    volumes:
      - ./backend/app:/app
      - ./backend/app/node_modules:/app/node_modules
    networks:
      - transcendence_network

# auth-service:
  exemple-webcomponent:
    build:
      context: ./exemple-webcomponent
      dockerfile: ./Dockerfile
    container_name: exemple-webcomponent
    environment:
      - NODE_ENV=development
    depends_on:
      - sqlite-service
    volumes:
      - ./exemple-webcomponent/app:/app
      - ./exemple-webcomponent/app/node_modules:/app/node_modules
    networks:
      - transcendence_network

# auth-service:
  exemple-external-container:
    build:
      context: ./exemple-external-container
      dockerfile: ./Dockerfile
    container_name: exemple-external-container
    environment:
      - NODE_ENV=development
    depends_on:
      - sqlite-service
    volumes:
      - ./exemple-external-container/app:/app
      - ./exemple-external-container/app/node_modules:/app/node_modules
    networks:
      - transcendence_network

#ajout d'un service de base de données
  sqlite-service:
    build:
      context: ./sqlite-service
      dockerfile: ./Dockerfile
    container_name: sqlite-service 
    volumes:
      - ./sqlite-service/app:/app #app source code
      - ./sqlite-service/data:/data #database data
      - ./sqlite-service/app/node_modules:/app/node_modules #node_modules
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - transcendence_network

  pong:
    build:
      context: ./pong
      dockerfile: ./Dockerfile
    container_name: pong
    environment:
      - NODE_ENV=development
    depends_on:
      - backend_services
    volumes:
      - ./pong/app:/app
      - ./pong/app/node_modules:/app/node_modules

  database-services:
    build:
      context: ./database-service
      dockerfile: ./Dockerfile
    container_name: database-services
    environment:
      - NODE_ENV=development
    volumes:
      - ./database-service/app:/app #app source code
      - ./database-service/app/node_modules:/app/node_modules #node_modules
    restart: always
    networks:
      - transcendence_network

# network and volumes
networks:
  transcendence_network:
    driver: bridge

volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      device: ./backend/app/build
      o: bind
  databases_data:
    driver: local
    driver_opts:
      type: none
      device: ./databases
      o: bind
  sqlite_data:
    driver: local
    driver_opts:
      type: none
      device: ./sqlite-service/data
      o: bind
  certs_data:
    driver: local
    driver_opts:
      type: none
      device: ./certs
      o: bind