user www-data;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    default_type  application/octet-stream;
    include       mime.types;
    # Définir la zone de mémoire partagée pour le contrôle de débit
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;
    include /etc/nginx/conf.d/*.conf;

}