    location /frontend-pong-module/ {
        proxy_pass http://frontend-pong-module:3000;
        proxy_set_header Host $host; # Required for subdomains
        proxy_set_header X-Real-IP $remote_addr; # Required for subdomains
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Required for subdomains
        proxy_set_header Upgrade $http_upgrade; # Required for websockets
        proxy_set_header Connection "upgrade"; # Required for websockets
    }