
    location / {
        proxy_pass http://frontend-services-vite:3000;        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /component-alias/ {
        #Warning: Change the proxy_pass to your component module name
        #Example: proxy_pass http://exemple-component-module:3000/
        # -proxy_pass must end with a slash (/) to work properly with the alias
        proxy_pass http://exemple-component-module:3000/;
        proxy_set_header Host $host; # Required for subdomains
        proxy_set_header X-Real-IP $remote_addr; # Required for subdomains
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Required for subdomains
        proxy_set_header Upgrade $http_upgrade; # Required for websockets
        proxy_set_header Connection "upgrade"; # Required for websockets
    }